{% set version = "2.12.0" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/locust/locust-{{ version }}.tar.gz
  sha256: 864fbbf3a6170a7a632f03c5d51d9e76c6e6a5adbdbd8f136078459f00173198

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=6.2
    - wheel
  run:
    - configargparse >=1.0
    - flask >=2.0.0
    - flask-basicauth >=0.2.0
    - flask-cors >=3.0.10
    - gevent >=20.12.1
    - geventhttpclient >=1.5.1
    - msgpack-python >=0.6.2
    - psutil >=5.6.7
    - python >=3.7
    - pywin32-on-windows
    - pyzmq >=22.2.1,<23.0.0
    - requests >=2.23.0
    - roundrobin >=0.0.2
    - typing-extensions >=3.7.4.3
    - werkzeug >=2.0.0

{% set skips = [
  "autostart_w_load_shape",
  "custom_arguments",
  "custom_exit_code",
  "default_headless_spawn_options_with_shape",
  "from_relative_path",
  "headless_spawn_options_wo_run_time",
  "no_content_length_streaming",
  "skip_logging",
  "web_options",
  "webserver",
] %}
test:
  requires:
    - coverage
    - cryptography
    - mock
    - pip
    - pyquery
    - pytest
    - pytest-cov
    - retry
  imports:
    - locust
  commands:
    - python -m pip check
    - python -c "import locust; assert locust.__version__ == '{{ PKG_VERSION }}'"
    - pip list | grep -E "locust\s*{{ PKG_VERSION | replace('.', '\.') }}"  # [unix]
    - locust --version
    - locust --help
    # make empty test fixture folder
    - python -c '__import__("pathlib").Path("locust/test").mkdir(parents=True)'
    # TODO: restore coverage threshold, dynamic code getting skipped, throwing many warnings --cov-fail-under 80
    - pytest --pyargs locust --cov locust -vv -k "not ({{ " or ".join(skips) }})" --cov-report term-missing:skip-covered --no-cov-on-fail
about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
