{% set version = "2.18.0" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/locust/locust-{{ version }}.tar.gz
  sha256: f8d668c2c33518c705664bc869791d58fc98ba8f1aadbf2335be36e4e681feae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.2
    - wheel
  run:
    - configargparse >=1.0
    - flask >=2.0.0
    - flask-basicauth >=0.2.0
    - flask-cors >=3.0.10
    - gevent >=20.12.1
    - geventhttpclient >=2.0.2
    - msgpack-python >=0.6.2
    - psutil >=5.6.7
    - python >=3.8
    - pywin32-on-windows
    - pyzmq >=22.2.1,!=23.0.0
    - requests >=2.23.0
    - roundrobin >=0.0.2
    - werkzeug >=2.0.0

{% set skips = [
  "autostart_w_load_shape",
  "custom_arguments",
  "custom_exit_code",
  "default_headless_spawn_options_with_shape",
  "from_relative_path",
  "headless_spawn_options_wo_run_time",
  "no_content_length_streaming",
  "skip_logging",
  "web_options",
  "webserver",
  # https://github.com/conda-forge/locust-feedstock/pull/82
  "autostart_mutliple_locustfiles_with_shape",
  "graceful_exit_when_keyboard_interrupt",
  "percentile_parameter",
  "run_autostart_with_multiple_locustfiles",
  "run_with_userclass_picker",
  "worker_indexes",
] %}
test:
  requires:
    - pip
    # https://github.com/locustio/locust/blob/master/tox.ini
    - cryptography
    - mock
    - pyquery
    - pytest-cov
    - retry
  imports:
    - locust
  commands:
    - pip check
    - python -c "import locust; assert locust.__version__ == '{{ PKG_VERSION }}'"
    - pip list | grep -E "locust\s*{{ PKG_VERSION | replace('.', '\.') }}"  # [unix]
    - locust --version
    - locust --help
    # make empty test fixture folder
    - python -c '__import__("pathlib").Path("locust/test").mkdir(parents=True)'
    # TODO: restore coverage threshold, dynamic code getting skipped, throwing many warnings --cov-fail-under 80
    - pytest --pyargs=locust --cov=locust --color=yes --tb=long -vv --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not ({{ " or ".join(skips) }})"
about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
